//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class a
    {
        public int ReportID { get; set; }
        public int ReporterID { get; set; }
        public int ReportedID { get; set; }
        public string Comment { get; set; }
        public System.DateTime Date { get; set; }
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public string Gender { get; set; }
        public bool LocationPermission { get; set; }
        public bool BlockStatus { get; set; }
        public bool ActiveStatus { get; set; }
        public string MobileNumber { get; set; }
    }
}
