//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminPhoto
    {
        public int PhotoID { get; set; }
        public string Link { get; set; }
        public bool DeleteStatus { get; set; }
        public int AdminID { get; set; }
    
        public virtual Admin Admin { get; set; }
    }
}
