//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Admin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Admin()
        {
            this.AdminPhotoes = new HashSet<AdminPhoto>();
        }

        public int AdminId { get; set; }
        [Display(Name = "First Name ")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "First Name is Required.")]
        [RegularExpression(@"[a-zA-Z]*", ErrorMessage = "only use alphabet")]
        public string FirstName { get; set; }

        [Display(Name = "Last Name ")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Last Name is Required.")]
        [RegularExpression(@"[a-zA-Z]*", ErrorMessage = "only use alphabet")]
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public bool IsEmailVerified { get; set; }
        public System.Guid ActivationCode { get; set; }
        public string ResetPasswordCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminPhoto> AdminPhotoes { get; set; }
    }
}
