//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CelebritySuggestion
    {
        public int SuggestionID { get; set; }
        public int Rate { get; set; }
        public System.DateTime Date { get; set; }
        public string Comment { get; set; }
        public int SuggestorId { get; set; }
        public int CelebrityID { get; set; }
    
        public virtual Celebrity Celebrity { get; set; }
        public virtual Celebrity Celebrity1 { get; set; }
        public virtual RateSuggestion RateSuggestion { get; set; }
        public virtual UserData UserData { get; set; }
    }
}
