//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class reportedPerson
    {
        public int ReportId { get; set; }
        public int ReporterId { get; set; }
        public int ReportedId { get; set; }
        public string Comment { get; set; }
        public System.DateTime Date { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}
