//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Search
    {
        public int SearchID { get; set; }
        public int SearchedPersonId { get; set; }
        public int SearcherId { get; set; }
        public System.DateTime date { get; set; }
        public int TypeId { get; set; }
    
        public virtual SearchType SearchType { get; set; }
        public virtual UserData UserData { get; set; }
        public virtual UserData UserData1 { get; set; }
    }
}
