//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacialRecognitionSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CelebrityPhoto
    {
        public int PhotoID { get; set; }
        public string Link { get; set; }
        public bool DeletedStatus { get; set; }
        public int CelibrityID { get; set; }
    
        public virtual Celebrity Celebrity { get; set; }
    }
}
