//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacialRecognitionSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RateSuggestion
    {
        public int SuggestionID { get; set; }
        public int SuggestorID { get; set; }
        public System.DateTime Date { get; set; }
        public int Rating { get; set; }
    
        public virtual CelebritySuggestion CelebritySuggestion { get; set; }
    }
}
